### ISSUE TITLE
Investigate statics

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nethsm-pkcs11#163]
Lots of `LazyStatics` are so because they are `Arc<Mutex>`, they may be replaceable by bare `Mutex`, getting rid of the `Arc`, potentially maybe also `thread_locals` instead so that the module can properly support multithreaded operation.

**Comment by ansiwen** [comment]
Some context: We need to pay attention to the different requirements of PKCS11 modules in different thread support modes. (See parameters of C_Initialize) With nginx there was (IIRC) the quirk that the initial process initialized the module already but didn't use it, then every worker fork initialized it again. So we need to handle initialization after forking of already initialized state (which can be tricky). That's one of the reasons why we switched from reqwest to ureq, because the first is using the tokio runtime, which was almost impossible to "repair" after forking.

**Comment by ansiwen** [comment]
No, not at a single place unfortunately. There is the PKCS11 spec, then there is this related issue https://github.com/tokio-rs/tokio/issues/1541. In general the issues with forking are: already created threads (will be missing) and file-descriptors (will be shared). So we would need to avoid both, at least before C_Initialize. I assume  that's the reason why @nponsard used the lazy statics.

**Comment by sosthene-nitrokey** [comment]
Thanks for the feedback. I will try the nginx example and try to make a minimal reproducer of the forking behaviour and add it to the CI.

**Comment by sosthene-nitrokey** [comment]
All remaining statics are necessary, and cannot be removed. Some of them were already moved to being `consts` or not lazy when appropriate.
