### ISSUE TITLE
Document usage with OpenSSL

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nethsm-pkcs11#82]
- [x] New dedicated documentation page for OpenSSL
- [x] use PKCS11SPY=/usr/lib64/[nethsm-pkcs11-v0.1.1-fedora.38.so](http://nethsm-pkcs11-v0.1.1-fedora.38.so/) openssl pkey -engine pkcs11 -inform ENGINE -in "pkcs11:object=nginx;type=public" -pubout to only request the public components of the key.
- [x] Usage as OpenSSL's provider (probably as an option but not exclusively because OpenSSL 1 is still around) https://github.com/latchset/pkcs11-provider

**Comment by nponsard** [comment]
The OpenSSL provider cannot be used by Nginx : 
https://github.com/nginx/nginx/blob/e5fc65976a479d3ae46f4ffb6334c2851d654234/src/event/ngx_event_openssl.c#L812C19-L812C19
This line here uses `BIO_new_file` instead of `OSSL_STORE_open`.

`OSSL_STORE_open` allows for non-file URIS to be parsed (here it would be a pkcs11 URI) whereas `BIO_new_file` only read a file on disk.
